#!/bin/bash

#########
# $Home #
#########
dotfiles=( xprofile Xresources zshrc )
for df in "${dotfiles[@]}"
do
    if [ ! -f $HOME/.$df ]
    then
        ln -s $HOME/Repositories/voidrice/$df $HOME/.$df
    else
        rm $HOME/.$df
        ln -s $HOME/Repositories/voidrice/$df $HOME/.$df
    fi
done


##########
# .local #
##########
if [ ! -d ~/.local ]
then
    mkdir ~/.local
fi

if [ ! -d ~/.local/bin ]
then
    ln -s ~/Repositories/voidrice/bin ~/.local/bin
else
    rm -r $HOME/.local/bin
    ln -s ~/Repositories/voidrice/bin ~/.local/bin
fi


###########
# .config #
###########
if [ ! -d $HOME/.config ]
then
    mkdir $HOME/.config
fi
configs=( bspwm compton dunst fontconfig gtkrc-2.0 gtk-3.0 nvim polybar rofi sxhkd )
for conf in "${configs[@]}"
do
    if [ ! -d $HOME/.config/$conf ]
    then
        ln -s $HOME/Repositories/voidrice/config/$conf ~/.config/$conf
    else
        rm -r ~/.config/$conf
        ln -s $HOME/Repositories/voidrice/config/$conf ~/.config/$conf
    fi
done
