#!/bin/sh

# key bindings
sxhkd &

# us to de layout
setxkbmap -rules evdev -model pc101 -layout de -variant us

# set cursor
xsetroot -cursor_name left_ptr

# polybar 
polybar bspwm-bar & 

# launch compton
compton & 

# Set some bsp specific stuff
bspc monitor -d           

bspc config border_width 3
bspc config window_gap 12
bspc config top_padding 18
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
