#!/bin/sh

# key bindings
sxhkd &

# us to de layout
setxkbmap -rules evdev -model pc101 -layout de -variant us

# set cursor
xsetroot -cursor_name left_ptr

# launch compton
compton &

# polybar
#launch_polybar

# wallpaper
feh --no-fehbg --bg-scale "$HOME/Repositories/voidrice/images/wallpaper.png" &

# keepassxc
keepassxc &

# external monitor
if [ -x $HOME/.local/bin/external_monitor ];then
    external_monitor
fi

# Set some bsp specific stuff
#bspc monitor -d          
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -n 1 -d I II III IV
#bspc monitor DP1-1 -n 2 -d V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 12
bspc config top_padding 26
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true

bspc config pointer_modifier mod4
bspc config click_to_focus false
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#111111"
bspc config active_border_color "#4488cc"
bspc config focused_border_color "#4488cc"
